/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Infomation;

/**
 *
 * @author ADMIN
 */
public class Main_View extends javax.swing.JFrame {
   public static int i=1;
   public static DAO connectDao;
    ArrayList<Infomation> listAI;
    /**
     * Creates new form Main_View
     */
    public Main_View() {
       initComponents();
        setResizable(false);
        BufferedImage iMage;
        try {
           
            iMage = ImageIO.read(new File("src/main.png"));
            //JsonReader imgURL=new JsonReader();
           
            //iMage = ImageIO.read(new URL(imgURL.get("hulk")));
            ImageIcon icon=new ImageIcon(iMage.getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), iMage.SCALE_SMOOTH));
            jLabel8.setIcon(icon);
        } catch (IOException ex) {
            
        }
       if(i==1){
            connectDao=new DAO();
            connectDao.getListInfo();
            i++;
        }
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnThaoTacTU = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnPlayWithAI = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("CHÀO MỪNG BẠN ĐẾN VỚI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("ENGLISH IS SO FUN");

        jButton1.setText("Thao tác với từ");

        jButton2.setText("Chơi");

        jButton3.setText("Chơi cùng AI");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 204));
        jLabel5.setText("ENGLISH IS SO FUN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 11, 296, 0);

        jLabel6.setFont(new java.awt.Font("Source Code Pro Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("CHÀO MỪNG BẠN ĐẾN VỚI");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(320, 40, 309, 43);

        jLabel7.setFont(new java.awt.Font("Source Code Pro Black", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 255));
        jLabel7.setText("ENGLISH IS SO FUN");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(339, 93, 231, 48);

        btnThaoTacTU.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnThaoTacTU.setForeground(new java.awt.Color(0, 51, 51));
        btnThaoTacTU.setText("THAO TÁC VỚI TỪ/CỤM TỪ");
        btnThaoTacTU.setActionCommand("Thao tác từ.cụm từ");
        btnThaoTacTU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnThaoTacTU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThaoTacTUActionPerformed(evt);
            }
        });
        jPanel2.add(btnThaoTacTU);
        btnThaoTacTU.setBounds(80, 175, 489, 51);

        btnPlay.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(0, 51, 51));
        btnPlay.setText("CHƠI");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jPanel2.add(btnPlay);
        btnPlay.setBounds(80, 253, 489, 51);

        btnPlayWithAI.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnPlayWithAI.setForeground(new java.awt.Color(0, 51, 51));
        btnPlayWithAI.setText("CHƠI CÙNG 'AI'");
        btnPlayWithAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayWithAIActionPerformed(evt);
            }
        });
        jPanel2.add(btnPlayWithAI);
        btnPlayWithAI.setBounds(80, 337, 489, 51);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, -80, 830, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThaoTacTUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThaoTacTUActionPerformed
        
        setVisible(false);
        ThaoTacVoiTu a=new ThaoTacVoiTu();
        
        
    }//GEN-LAST:event_btnThaoTacTUActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        setVisible(false);
        Game a= new Game();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnPlayWithAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayWithAIActionPerformed
        listAI=new ArrayList<>();
        for (Infomation listAI1 : DAO.list) {
            if(listAI1.getTemp()>5)
                listAI.add(listAI1);
        }
        if(listAI.size()==0) 
            JOptionPane.showMessageDialog(null, "Bạn chơi chế độ thường trước nhé");
        else{
            String error="";
            for (Infomation listAI1 : listAI) {
                error+=listAI1.getTu()+"\n";
            }
            JOptionPane.showMessageDialog(null,"Đây là danh sách các từ bạn sai nhiều nhất(>5)\n"+error);
            JOptionPane.showMessageDialog(null, "Hãy luyện tập thật nhiều để thành thạo chúng nhé");
          
        }
        
    }//GEN-LAST:event_btnPlayWithAIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                Main_View a= new Main_View();
                a.setVisible(true);
                a.setLocationRelativeTo(null);
                a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                a.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlayWithAI;
    private javax.swing.JButton btnThaoTacTU;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
